#!/bin/sh
# vim: set ts=4:
set -eu

cd "$(dirname "$0")/.."
. script/utils.sh

if [ -z "${encrypted_8b8accbb892a_key:-}" ]; then
	ewarn 'Decryption key is not available, skipping deploy.'; exit 0
fi

einfo 'Decrypting .deploykey...'
openssl aes-256-cbc \
	-K "$encrypted_8b8accbb892a_key" \
	-iv "$encrypted_8b8accbb892a_iv" \
	-in .deploykey.enc -out .deploykey -d
chmod 600 .deploykey
